import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Consent from "@/components/consent";
import ScrollManager from "@/components/scroll";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<main className="flex flex-col items-center relative">
					<nav className="sticky top-0 w-full flex justify-center border-b border-b-foreground/10 h-16 bg-white">
						<div className="w-full max-w-5xl flex justify-center items-center p-3 px-5 text-xl font-semibold">
							User Consent
						</div>
					</nav>
					{/* <div className="flex flex-col gap-20 max-w-5xl p-5 pb-[10rem]">
						{children}
					</div>
					<footer className="fixed inset-x-0 bottom-0 w-full flex items-center justify-center border-t border-t-foreground/10 p-4 bg-white">
						<Consent />
					</footer> */}
					<ScrollManager>{children}</ScrollManager>
				</main>
			</body>
		</html>
	);
}
